kind: pipeline
type: docker
name: default

steps:
  - name: set-remote
    image: docker:git
    environment:
      GITHUB_PAT:
        from_secret: GITHUB_PAT
    commands:
      - env
      - echo $GITHUB_PAT
      - CLONE_URL=${DRONE_GIT_HTTP_URL#"https://"}
      - echo $CLONE_URL
      - git remote set-url origin "https://$GITHUB_PAT@$CLONE_URL"
    when:
      branch:
        - main
      event:
        - push

  - name: release
    image: gembaadvantage/uplift
    commands:
      - uplift release --fetch-all
    when:
      branch:
        - main
      event:
        - push
