kind: pipeline
type: docker
name: default

steps:
  - name: set-remote
    image: docker:git
    environment:
      GITHUB_PAT:
        from_secret: github_pat
    commands:
      - CLONE_URL=${DRONE_GIT_HTTP_URL##https://}
      - git remote set-url origin https://$GITHUB_PAT@$CLONE_URL
    when:
      branch:
        - main
      event:
        - push

  - name: release
    image: gembaadvantage/uplift
    commands:
      - uplift release --fetch-all
    when:
      branch:
        - main
      event:
        - push
---
kind: secret
name: github_pat
data: VLO71Ad3QSALQjELGKg5U7r92823a9e4vmu7xUw3LJ9xKwZu8XJmKG+7SykRDblo2ozeH0ZhrYTuChOPxS1Mn9jnRU8=
