kind: pipeline
type: docker
name: default

steps:
  - name: release
    image: gembaadvantage/uplift
    commands:
      - uplift release --fetch-all
    when:
      branch:
        - main
      event:
        - push
