bumps:
  - # The path of the file relative to where uplift is executed
    file: version.json
    paths:
      - ".version"

  - file: config.toml
    paths:
      - ".package.version"

  - file: test.yml
    paths:
      - path: ".properties.metadata.version"
        semver: no
