version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    commands:
      - curl https://raw.githubusercontent.com/gembaadvantage/uplift/main/scripts/install | bash
  pre_build:
    commands:
      - git checkout ${CODEBUILD_SOURCE_VERSION##"refs/heads/"}
  build:
    commands:
      - uplift release
